[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
fund_me_crowd = "3thsLxeasr6oWXzGpYqHJkndBAqyVLEPtgpvGsJsDQMm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/gaurav/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
